version: 2
updates:
  - package-ecosystem: 'maven'
    directories:
      - '/'
      - '/modules/*'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '/modules/*'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
