<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <groupId>parent</groupId>
  <artifactId>parent</artifactId>
  <version>parent</version>
  <packaging>pom</packaging>

  <modules>
    <module>modules/agent</module>
    <module>modules/launcher</module>
    <module>modules/plugin</module>
  </modules>

  <distributionManagement>
    <repository>
      <id>github</id>
      <url>https://maven.pkg.github.com/WebMCDevelopment/wlib/</url>
    </repository>
  </distributionManagement>

  <properties>
    <proj.name>WLIB</proj.name>
    <proj.afct>wlib</proj.afct>
    <proj.pckg>xyz.webmc.${proj.afct}</proj.pckg>
    <proj.vers>1.3.4-SNAPSHOT</proj.vers>
    <proj.athr>Colbster937</proj.athr>

    <plugin.main>${proj.pckg}.internal.${proj.name}BukkitPlugin</plugin.main>
    <plugin.deps>["PlaceholderAPI", "LuckPerms", "Essentials", "EaglercraftXServer", "EaglercraftXBackendRPC"]</plugin.deps>

    <agent.main>${proj.pckg}.internal.agent.AgentMain</agent.main>
    <agent.bdge>${proj.pckg}.internal.agent.AgentBridge</agent.bdge>
    <agent.boot>${proj.pckg}.internal.agent.AgentBootstrap</agent.boot>

    <launcher.main>${proj.pckg}.internal.launcher.LauncherMain</launcher.main>

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>17</maven.compiler.release>
    <maven.deploy.skip>true</maven.deploy.skip>
  </properties>

  <build>
    <finalName>${project.artifactId}-${proj.vers}</finalName>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.5.0</version>
        <inherited>false</inherited>

        <executions>
          <execution>
            <id>copy-resources</id>
            <phase>initialize</phase>

            <goals>
              <goal>copy-resources</goal>
            </goals>

            <configuration>
              <outputDirectory>${project.build.directory}/resources</outputDirectory>
              <resources>
                <resource>
                  <directory>modules/_build/resources</directory>
                  <filtering>true</filtering>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.mycila</groupId>
        <artifactId>license-maven-plugin</artifactId>
        <version>5.1.2</version>
        <inherited>false</inherited>

        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>format</goal>
            </goals>
          </execution>
        </executions>

        <configuration>
          <aggregate>true</aggregate>
          <basedir>${project.basedir}</basedir>
          <licenseSets>
            <licenseSet>
              <header>${project.build.directory}/resources/licenseHeader.txt</header>
              <includes>
                <include>modules/**/src/**/*.java</include>
              </includes>
            </licenseSet>
          </licenseSets>
        </configuration>

        <dependencies>
          <dependency>
            <groupId>com.mycila</groupId>
            <artifactId>license-maven-plugin-git</artifactId>
            <version>5.1.2</version>
          </dependency>
        </dependencies>
      </plugin>

      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>3.10.3</version>
        <inherited>false</inherited>

        <executions>
          <execution>
            <phase>process-sources</phase>
            <goals>
              <goal>apply</goal>
            </goals>
          </execution>
        </executions>

        <configuration>
          <java>
            <includes>
              <include>modules/**/src/**/*.java</include>
            </includes>

            <cleanthat>
              <sourceJdk>${maven.compiler.release}</sourceJdk>
            </cleanthat>

            <removeUnusedImports />

            <importOrder>
              <order>${proj.pckg},java,javax,,\#${proj.pckg},\#java,\#javax,\#</order>
            </importOrder>

            <trimTrailingWhitespace />

            <endWithNewline />

            <replaceRegex>
              <name>newline after license header</name>
              <searchRegex>\*/\R*package</searchRegex>
              <replacement>*/&#10;&#10;package</replacement>
            </replaceRegex>
          </java>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>3.6.0</version>
        <inherited>false</inherited>
        
        <executions>
          <execution>
            <id>checkstyle</id>
            <phase>process-resources</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>

        <configuration>
          <configLocation>${project.build.directory}/resources/checkstyle.xml</configLocation>
          <includeTestSourceDirectory>false</includeTestSourceDirectory>
          <failOnViolation>true</failOnViolation>
          <consoleOutput>true</consoleOutput>
        </configuration>
      </plugin>
    </plugins>

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.5.1</version>
          <configuration>
            <archive>
              <addMavenDescriptor>false</addMavenDescriptor>
            </archive>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
