name: ${plugin.name}
version: ${plugin.vers}
main: ${plugin.pckg}.${plugin.name}BukkitPlugin
authors: ["${plugin.athr}"]
folia-supported: true
api-version: 1.13

dependencies:
  server: ${plugin.deps.mdrn}