-keepattributes *Annotation*,Signature,EnclosingMethod,InnerClasses,SourceFile,LineNumberTable
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontoptimize
-allowaccessmodification
-ignorewarnings
-dontwarn
-dontnote

-adaptresourcefilecontents plugin.yml,build.properties,META-INF/MANIFEST.MF

-repackageclasses ${proj.pckg}.internal
-keeppackagenames !${proj.pckg}.internal.**

-keep class !${proj.pckg}.internal.** { *; }

-keep,allowobfuscation class ${proj.pckg}.internal.*, ${proj.pckg}.internal.agent.**, ${proj.pckg}.internal.launcher.** {
  *;
}

-keepclassmembernames class * {
  public static void main(java.lang.String[]);
}

-keepclassmembernames class ${proj.pckg}.internal.compat.** {
  public <fields>;
  public <methods>;
}

-keepclassmembernames class ${proj.pckg}.internal.util.** {
  public *** _*(...);
}
